


// import { Inter } from "next/font/google";
import { Header } from "./components/shared/Header";
import { Footer } from "./components/shared/Footer";
import "app/sass/globals.sass";



import {Roboto} from 'next/font/google';
import { Hero } from "./components/home/Hero";
import { Descripcion } from "./components/home/Description";
const roboto = Roboto({

  weight:["100","300","500"],
  subsets:["latin"],
})

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Future world",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">

      
      <body className={roboto.className} >
      <Header />
      {/* <Hero />
      <Descripcion /> */}
        
        {children}

<Footer />
      
      </body>
    </html>
  );
}
